AllCops:
  Exclude:
    - archive/**/*
    - vendor/**/*

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - '*.gemspec'
    - lib/github_records_archiver/cli.rb

Metrics/LineLength:
  Exclude:
    - spec/**/*
    - lib/github_records_archiver/cli.rb

Metrics/MethodLength:
  Exclude:
    - lib/github_records_archiver/cli.rb
    - spec/spec_helper.rb

Metrics/AbcSize:
  Exclude:
    - lib/github_records_archiver/cli.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - spec/spec_helper.rb

Layout/IndentHeredoc:
  Enabled: false
